In [1]:
# 사전 준비
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import warnings
plt.style.use('seaborn')
sns.set(font_scale=2.5)

warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
import matplotlib
from matplotlib import font_manager, rc
import platform

if platform.system() == 'Windows':
# 윈도우인 경우
    font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
    rc('font', family=font_name)
else:    
# Mac 인 경우
    rc('font', family='AppleGothic')
    
matplotlib.rcParams['axes.unicode_minus'] = False

In [3]:
sample = pd.read_csv('../input/final.csv')

print("sample.shape:", sample.shape)

# 초기 샘플 데이터
sample

sample.shape: (72250, 13)

,사고내용,도로형태 대분류,기상상태,차량년식,가해자성별,가해자나이,요일,가해차종,노면상태,보행자이동,빛 세기,사고 위치,사고 조절
6,3,0.0,1,8.0,2.0,3.332205,5,3.0,1.0,0.0,7,2.0,2.0
8,3,0.0,1,1.0,1.0,3.218876,5,9.0,1.0,2.0,1,1.0,2.0
14,3,0.0,1,1.0,2.0,3.178054,4,9.0,1.0,0.0,1,8.0,4.0
25,3,0.0,1,8.0,2.0,3.891820,7,9.0,1.0,0.0,1,8.0,4.0
26,3,0.0,1,7.0,2.0,3.871201,5,9.0,1.0,3.0,1,8.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285297,3,0.0,1,12.0,2.0,3.931826,3,9.0,2.0,1.0,4,1.0,4.0
285307,3,0.0,1,11.0,2.0,3.218876,4,9.0,2.0,0.0,1,8.0,4.0
285312,3,0.0,2,7.0,2.0,4.330733,7,9.0,2.0,0.0,1,1.0,4.0
285313,3,0.0,2,4.0,1.0,3.044522,7,9.0,2.0,0.0,1,7.0,4.0
285314,3,0.0,2,4.0,1.0,3.044522,7,9.0,2.0,0.0,1,7.0,4.0

In [4]:
from imblearn.combine import *
from imblearn.over_sampling import *

In [5]:
sample

,사고내용,도로형태 대분류,기상상태,차량년식,가해자성별,가해자나이,요일,가해차종,노면상태,보행자이동,빛 세기,사고 위치,사고 조절
6,3,0.0,1,8.0,2.0,3.332205,5,3.0,1.0,0.0,7,2.0,2.0
8,3,0.0,1,1.0,1.0,3.218876,5,9.0,1.0,2.0,1,1.0,2.0
14,3,0.0,1,1.0,2.0,3.178054,4,9.0,1.0,0.0,1,8.0,4.0
25,3,0.0,1,8.0,2.0,3.891820,7,9.0,1.0,0.0,1,8.0,4.0
26,3,0.0,1,7.0,2.0,3.871201,5,9.0,1.0,3.0,1,8.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285297,3,0.0,1,12.0,2.0,3.931826,3,9.0,2.0,1.0,4,1.0,4.0
285307,3,0.0,1,11.0,2.0,3.218876,4,9.0,2.0,0.0,1,8.0,4.0
285312,3,0.0,2,7.0,2.0,4.330733,7,9.0,2.0,0.0,1,1.0,4.0
285313,3,0.0,2,4.0,1.0,3.044522,7,9.0,2.0,0.0,1,7.0,4.0
285314,3,0.0,2,4.0,1.0,3.044522,7,9.0,2.0,0.0,1,7.0,4.0

In [6]:
sample = sample.iloc[np.random.permutation(len(sample))]

y = sample.loc[:, sample.columns == '사고내용']
x = sample.loc[:, sample.columns != '사고내용']

In [7]:
x_samp , y_samp = ADASYN(random_state = 20000).fit_sample(x,y)
#x_samp2, y_samp2 = SMOTETomek(random_state = 4).fit_sample(x,y)

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_samp, y_samp, test_size=0.2,random_state = 1)
#x_train, x_test, y_train, y_test = train_test_split(x_samp2, y_samp2, test_size=0.2)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
pred_knn = knn.predict(x_test)
val_knn = (pred_knn == y_test["사고내용"]).mean()
val_knn

0.8657821007559339

In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,pred_knn,target_names=['class 0','class 1','class 2']))
cm = confusion_matrix(y_test,pred_knn)
print('Confusion matrix: \n',cm)

              precision    recall  f1-score   support

     class 0       0.94      0.99      0.97     12495
     class 1       0.78      0.90      0.84     12845
     class 2       0.90      0.70      0.78     12494

    accuracy                           0.87     37834
   macro avg       0.87      0.87      0.86     37834
weighted avg       0.87      0.87      0.86     37834

Confusion matrix:
 [[12425    46    24]
 [  236 11614   995]
 [  551  3226  8717]]

In [10]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier

tree = DecisionTreeClassifier()
model = RandomForestClassifier()
model2 = BaggingClassifier()
model.fit(x_train,y_train)
model2.fit(x_train,y_train)
tree.fit(x_train,y_train)

pred = tree.predict(x_test)
pred_m1 = model.predict(x_test)
pred_m2 = model2.predict(x_test)
val = (pred == y_test["사고내용"]).mean()
val_m1 = (pred_m1 == y_test["사고내용"]).mean()
val_m2 = (pred_m2 == y_test["사고내용"]).mean()
print(val , val_m1, val_m2)

0.8915261405085373 0.9286091875033039 0.9095522545858222

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,pred_m1,target_names=['class 0','class 1','class 2']))
cm = confusion_matrix(y_test,pred_m1)
print('Confusion matrix: \n',cm)

              precision    recall  f1-score   support

     class 0       0.99      0.99      0.99     12495
     class 1       0.91      0.89      0.90     12845
     class 2       0.89      0.91      0.90     12494

    accuracy                           0.93     37834
   macro avg       0.93      0.93      0.93     37834
weighted avg       0.93      0.93      0.93     37834

Confusion matrix:
 [[12389    42    64]
 [  101 11382  1362]
 [   78  1054 11362]]