In [1]:
# 사전 준비
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import warnings

plt.style.use('seaborn')
sns.set(font_scale=2.5)

warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
import matplotlib
from matplotlib import font_manager, rc
import platform

if platform.system() == 'Windows':
# 윈도우인 경우
    font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
    rc('font', family=font_name)
else:    
# Mac 인 경우
    rc('font', family='AppleGothic')
    
matplotlib.rcParams['axes.unicode_minus'] = False

In [3]:
sample = pd.read_csv('../input/final.csv')

print("sample.shape:", sample.shape)

# 초기 샘플 데이터
sample

sample.shape: (72250, 13)

,사고내용,도로형태 대분류,기상상태,차량년식,가해자성별,가해자나이,요일,가해차종,노면상태,보행자이동,빛 세기,사고 위치,사고 조절
6,3,0.0,1,8.0,2.0,3.332205,5,3.0,1.0,0.0,7,2.0,2.0
8,3,0.0,1,1.0,1.0,3.218876,5,9.0,1.0,2.0,1,1.0,2.0
14,3,0.0,1,1.0,2.0,3.178054,4,9.0,1.0,0.0,1,8.0,4.0
25,3,0.0,1,8.0,2.0,3.891820,7,9.0,1.0,0.0,1,8.0,4.0
26,3,0.0,1,7.0,2.0,3.871201,5,9.0,1.0,3.0,1,8.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285297,3,0.0,1,12.0,2.0,3.931826,3,9.0,2.0,1.0,4,1.0,4.0
285307,3,0.0,1,11.0,2.0,3.218876,4,9.0,2.0,0.0,1,8.0,4.0
285312,3,0.0,2,7.0,2.0,4.330733,7,9.0,2.0,0.0,1,1.0,4.0
285313,3,0.0,2,4.0,1.0,3.044522,7,9.0,2.0,0.0,1,7.0,4.0
285314,3,0.0,2,4.0,1.0,3.044522,7,9.0,2.0,0.0,1,7.0,4.0